title: HuWeifeng
subtitle: HuWF's personal homepage
logo: /assets/img/header.png
description: Machine learning，Deep learning，Data analysis   
email: 674649741@qq.com
github: HuWF
show_downloads: False
theme: jekyll-theme-minimal
